package com.example.aproject.core.database.entities

import androidx.room.ColumnInfo
import androidx.room.Entity
import androidx.room.PrimaryKey

/**
 * Room entity for the `advice` table.
 *
 * Stores the text of an advice and the timestamp (milliseconds since epoch)
 * when it was saved. The [id] is auto-generated by Room.
 */
@Entity(tableName = "advice")
data class AdviceEntity(
    @PrimaryKey(autoGenerate = true)
    val id: Long = 0,
    val advice: String,
    @ColumnInfo(name = "time_creation")
    val timeCreation: Long = System.currentTimeMillis()
)
